# Configuration similar to the Wikimedia farm
'(?<lang>[a-z]+)\.(?<family>[a-z]+)\.org':
    
    variables:
        
        - variable: 'family'
          file: '$family.dblist'
        
        - variable: 'lang'
          type: 'language'
    
    data: '/srv/data/org/$family/$lang'
    cache: '/tmp/mw-cache/org-$version-$family-$lang'
    config:
      - 'org/InitialiseSettings.php'
      - 'org/PrivateSettings.php'

# Configuration for a small wiki farm
'(?<client>[a-z]+)-(?<wiki>[a-z]+)\.example\.com':
    
    variables:
        
        - variable: 'client'
          file: 'clients.yml'
          config: 'com/example/$client/InitialiseSettings.yml'
        
        - variable: 'wiki'
          file: '$client/wikis.yml'
    
    data: '/srv/data/com/example/$client/$wiki'
    cache: '/tmp/mw-cache/com-example-$version-$client-$wiki'
    config: 'com/example/InitialiseSettings.yml'
    post-config:
      - 'com/example/PrivateSettings.yml'
      - 'com/example/GlobalSettings.php'
