<?php

// autoload.php @generated by MediaWikiFarm
// @codeCoverageIgnoreStart

$extensions = $GLOBALS['wgMediaWikiFarm']->getConfiguration( 'composer' );

if( count( $extensions ) ) {
	foreach( $extensions as $extension ) {

		require_once __DIR__ . '/composer' . substr( md5( $extension ), 0, 8 ) . '/autoload_real.php';
		call_user_func( array( 'ComposerAutoloaderInit' . substr( md5( $extension ), 0, 8 ), 'getLoader' ) );
	}
	unset( $extensions );
	unset( $extension );
	return;
}
unset( $extensions );

require_once __DIR__ . '/composer' . '/autoload_real.php';
ComposerAutoloaderInitDEFAULT::getLoader();
// @codeCoverageIgnoreEnd
